CREATE TYPE public.app_role AS ENUM ('admin', 'moderator', 'user');
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL, UNIQUE(user_id, role));
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read own roles" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
CREATE TABLE public.artwork_poses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), category text NOT NULL CHECK (category IN ('ship','rocket')), subject text NOT NULL CHECK (length(subject) BETWEEN 1 AND 60), pose text NOT NULL CHECK (pose IN ('idle','cast','submerged','haul','flight','explosion','fire','smoke','fade')), image_path text NOT NULL UNIQUE, created_by uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.artwork_poses TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.artwork_poses TO authenticated;
GRANT ALL ON public.artwork_poses TO service_role;
ALTER TABLE public.artwork_poses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "view artwork" ON public.artwork_poses FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "admins upload artwork" ON public.artwork_poses FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(), 'admin') AND created_by = auth.uid() AND image_path LIKE auth.uid()::text || '/%');
CREATE POLICY "admins edit artwork" ON public.artwork_poses FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "admins remove artwork" ON public.artwork_poses FOR DELETE TO authenticated USING (public.has_role(auth.uid(), 'admin'));
CREATE TRIGGER artwork_poses_touch BEFORE UPDATE ON public.artwork_poses FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
DROP POLICY IF EXISTS fleet_layout_insert ON public.fleet_layout;
DROP POLICY IF EXISTS fleet_layout_update ON public.fleet_layout;
CREATE POLICY "admins publish fleet layouts" ON public.fleet_layout FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "admins update fleet layouts" ON public.fleet_layout FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));